// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnozwaewntvatstutros.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhub3p3YWV3bnR2YXRzdHV0cm9zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5NDE3NzgsImV4cCI6MjA1MTUxNzc3OH0.QGpfCnUpBaY0XkXFPFslnN8xJOrMuqWcY-Kw8fH0ip8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);